language: objective-c #1
osx_image:  xcode9.1 #2
xcode_project: LevelMeter.xcodeproj #3
xcode_scheme: LevelMeter #4
xcode_sdk: iphonesimulator9.3 #5

script:
    xcodebuild clean && xcodebuild -project LevelMeter.xcodeproj -scheme LevelMeter -sdk iphonesimulator9.3 CODE_SIGNING_REQUIRED=NO

