language: objective-c #1
osx_image:  xcode9.1 #2
xcode_project: LevelMeter.xcodeproj #3
xcode_scheme: LevelMeter #4
xcode_sdk: iphonesimulator9.3 #5

before_script:
    cd LevelMeter

script:
    xcodebuild clean && xcodebuild -project LevelMeter/LevelMeter.xcodeproj -scheme LevelMeter -destination "platform=iOS Simulator,name=iPhone 7,OS=10.0" CODE_SIGNING_REQUIRED=NO

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
